DROP DATABASE IF EXISTS searchapp;
DROP USER IF EXISTS searchapp_user;

CREATE USER searchapp_user IDENTIFIED BY 'dbuser321';
CREATE DATABASE seachapp CHARACTER SET utf8;
GRANT ALL PRIVILEGES ON seachapp.* TO searchapp_user WITH GRANT OPTION;

USE seachapp;

CREATE TABLE topic (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NULL DEFAULT NULL,
    description VARCHAR(5000) NULL DEFAULT NULL,
    text_field_1 VARCHAR(5000) NULL DEFAULT NULL,
    text_field_2 VARCHAR(5000) NULL DEFAULT NULL,
    created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
)
ENGINE=InnoDB;
